#!/usr/bin/env node
/**
 * Export complete Supabase database schema
 * Run: node scripts/export-schema.js
 */

const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Error: Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function exportSchema() {
  console.log('🔍 Fetching database schema...\n');

  // Query to get all tables and their columns
  const { data: tables, error: tablesError } = await supabase.rpc('get_schema_info');
  
  if (tablesError) {
    console.error('Error fetching schema:', tablesError);
    
    // Fallback: Use information_schema
    const query = `
      SELECT 
        t.table_name,
        json_agg(
          json_build_object(
            'column_name', c.column_name,
            'data_type', c.data_type,
            'is_nullable', c.is_nullable,
            'column_default', c.column_default,
            'character_maximum_length', c.character_maximum_length,
            'numeric_precision', c.numeric_precision,
            'numeric_scale', c.numeric_scale
          ) ORDER BY c.ordinal_position
        ) as columns
      FROM information_schema.tables t
      JOIN information_schema.columns c ON t.table_name = c.table_name
      WHERE t.table_schema = 'public' 
        AND t.table_type = 'BASE TABLE'
      GROUP BY t.table_name
      ORDER BY t.table_name;
    `;
    
    const { data, error } = await supabase.rpc('exec_sql', { query });
    
    if (error) {
      console.error('Fallback query also failed:', error);
      console.log('\nℹ️  Please run this query directly in Supabase SQL Editor and save the output:\n');
      console.log(query);
      return;
    }
    
    return generateMarkdown(data);
  }
  
  return generateMarkdown(tables);
}

function generateMarkdown(tables) {
  let markdown = `# Database Schema Documentation

**Last Updated:** ${new Date().toISOString()}
**Auto-generated:** This file is automatically generated. Do not edit manually.

---

## Overview

This document contains the complete schema for all database tables in the application.

**⚠️ CRITICAL RULE:** Always reference this document when:
- Writing database queries
- Creating new API endpoints
- Modifying existing queries
- Debugging database-related issues

---

`;

  // Add table of contents
  markdown += `## Table of Contents\n\n`;
  tables.forEach(table => {
    markdown += `- [${table.table_name}](#${table.table_name.toLowerCase()})\n`;
  });
  markdown += `\n---\n\n`;

  // Add detailed table information
  tables.forEach(table => {
    markdown += `## ${table.table_name}\n\n`;
    markdown += `### Columns\n\n`;
    markdown += `| Column Name | Data Type | Nullable | Default | Notes |\n`;
    markdown += `|-------------|-----------|----------|---------|-------|\n`;
    
    table.columns.forEach(col => {
      const dataType = col.numeric_precision 
        ? `${col.data_type}(${col.numeric_precision},${col.numeric_scale})`
        : col.character_maximum_length
        ? `${col.data_type}(${col.character_maximum_length})`
        : col.data_type;
      
      markdown += `| ${col.column_name} | ${dataType} | ${col.is_nullable} | ${col.column_default || '-'} | |\n`;
    });
    
    markdown += `\n`;
  });

  markdown += `\n---\n\n`;
  markdown += `## Maintenance\n\n`;
  markdown += `**To update this document:**\n`;
  markdown += `\`\`\`bash\n`;
  markdown += `node scripts/export-schema.js\n`;
  markdown += `\`\`\`\n\n`;
  markdown += `**After any database migration:**\n`;
  markdown += `1. Run the export script\n`;
  markdown += `2. Commit the updated SCHEMA.md\n`;
  markdown += `3. Reference it in your code\n`;

  // Write to file
  const outputPath = path.join(__dirname, '..', 'SCHEMA.md');
  fs.writeFileSync(outputPath, markdown);
  
  console.log(`✅ Schema documentation generated: ${outputPath}`);
  console.log(`📄 Total tables documented: ${tables.length}`);
  
  return markdown;
}

// Alternative: Direct SQL query to paste in Supabase
console.log(`
📋 ALTERNATIVE METHOD:
If the script fails, run this query in Supabase SQL Editor:

SELECT 
  t.table_name,
  c.column_name,
  c.data_type,
  c.is_nullable,
  c.column_default,
  c.character_maximum_length,
  c.numeric_precision,
  c.numeric_scale,
  c.ordinal_position
FROM information_schema.tables t
JOIN information_schema.columns c ON t.table_name = c.table_name
WHERE t.table_schema = 'public' 
  AND t.table_type = 'BASE TABLE'
ORDER BY t.table_name, c.ordinal_position;

Then format the output into SCHEMA.md manually.
`);

exportSchema().catch(console.error);
