-- Create ticket_messages table for support ticket conversations
-- Links messages to support tickets for full conversation history

CREATE TABLE IF NOT EXISTS ticket_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  sender_type VARCHAR(20) NOT NULL CHECK (sender_type IN ('customer', 'admin', 'ai', 'system')),
  sender_name VARCHAR(255),
  message TEXT NOT NULL,
  is_ai BOOLEAN DEFAULT FALSE,
  is_private BOOLEAN DEFAULT FALSE, -- Admin-only messages
  attachments JSONB DEFAULT '[]'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id ON ticket_messages(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_user_id ON ticket_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_sender_type ON ticket_messages(sender_type);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_is_ai ON ticket_messages(is_ai);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_is_private ON ticket_messages(is_private);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_created_at ON ticket_messages(created_at DESC);

-- Enable RLS
ALTER TABLE ticket_messages ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Customers can view their own ticket messages (non-private only)
CREATE POLICY "Customers can view their ticket messages"
  ON ticket_messages FOR SELECT
  USING (
    is_private = FALSE
    AND ticket_id IN (
      SELECT id FROM support_tickets 
      WHERE customer_id IN (
        SELECT id FROM customers WHERE user_id = auth.uid()
      )
    )
  );

-- Customers can create messages on their own tickets
CREATE POLICY "Customers can create ticket messages"
  ON ticket_messages FOR INSERT
  WITH CHECK (
    sender_type = 'customer'
    AND ticket_id IN (
      SELECT id FROM support_tickets 
      WHERE customer_id IN (
        SELECT id FROM customers WHERE user_id = auth.uid()
      )
    )
  );

-- Reps can view messages on tickets they created (non-private only)
CREATE POLICY "Reps can view their ticket messages"
  ON ticket_messages FOR SELECT
  USING (
    (is_private = FALSE OR EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    ))
    AND ticket_id IN (
      SELECT id FROM support_tickets 
      WHERE created_by_rep = auth.uid()
      OR EXISTS (
        SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
      )
    )
  );

-- Reps can create messages on tickets they created
CREATE POLICY "Reps can create ticket messages"
  ON ticket_messages FOR INSERT
  WITH CHECK (
    sender_type IN ('admin', 'ai')
    AND ticket_id IN (
      SELECT id FROM support_tickets 
      WHERE created_by_rep = auth.uid()
      OR EXISTS (
        SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
      )
    )
  );

-- Admins can view all ticket messages (including private)
CREATE POLICY "Admins can view all ticket messages"
  ON ticket_messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can create any ticket messages
CREATE POLICY "Admins can create ticket messages"
  ON ticket_messages FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can update ticket messages
CREATE POLICY "Admins can update ticket messages"
  ON ticket_messages FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can delete ticket messages
CREATE POLICY "Admins can delete ticket messages"
  ON ticket_messages FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Trigger for updated_at
CREATE TRIGGER update_ticket_messages_updated_at
  BEFORE UPDATE ON ticket_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE ticket_messages IS 'Messages within support tickets for full conversation history';
COMMENT ON COLUMN ticket_messages.is_private IS 'Admin-only messages not visible to customers';
COMMENT ON COLUMN ticket_messages.is_ai IS 'True if message was generated by AI assistant';
COMMENT ON COLUMN ticket_messages.attachments IS 'Array of attachment objects with urls and metadata';
