-- Add columns to capture Shopify payment transaction details
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS shopify_payment_gateway TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shopify_payment_method TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS card_brand TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS card_last_four TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS card_exp_month INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS card_exp_year INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS billing_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS billing_address_line1 TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS billing_city TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS billing_state TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS billing_zip TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS billing_country TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shopify_order_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shopify_transaction_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shopify_payment_amount DECIMAL(10,2) DEFAULT NULL;

