-- Add is_ai column to ticket_messages table to track AI-generated responses

ALTER TABLE ticket_messages 
ADD COLUMN IF NOT EXISTS is_ai BOOLEAN DEFAULT FALSE;

-- Add index for filtering AI messages
CREATE INDEX IF NOT EXISTS idx_ticket_messages_is_ai ON ticket_messages(is_ai);

-- Allow null user_id for AI messages
ALTER TABLE ticket_messages
ALTER COLUMN user_id DROP NOT NULL;

COMMENT ON COLUMN ticket_messages.is_ai IS 'True if message was generated by AI assistant';
